# Generated by Django 4.2.2 on 2023-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_item_chat_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='N/A', max_length=128),
            preserve_default=False,
        ),
    ]
