# Generated by Django 4.2.2 on 2023-07-08 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='latestInteraction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
