# Generated by Django 4.2.2 on 2023-06-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendedUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='test',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
